spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 비공개
            clientSecret: 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
            scope:
              - email
              - profile






          naver:
            clientId: 비공개
            clientSecret: L4Tr_lzK4s
            scope:
              - name
              - email
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize # 뷰에서 /oauth2/authorization/naver을 호출하면 이 경로로 자동 호출이 되어 인증이 실행된다.
            tokenUri: https://nid.naver.com/oauth2.0/token # 토큰을 받는 주소
            userInfoUri: https://openapi.naver.com/v1/nid/me # 프로필 정보를 받기 위해서 호출하는 경로
            userNameAttribute: response # 회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해준다.
